#############################################################################
# Makefile for building: bin/slade-qt
# Generated by qmake (2.01a) (Qt 4.6.2) on: Mon May 3 23:17:26 2010
# Project:  slade-qt.pro
# Template: app
# Command: /usr/bin/qmake -unix DESTDIR=./bin MOC_DIR=./src/moc CONFIG+=release OBJECTS_DIR=./obj/release -o Makefile slade-qt.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Isrc -Isrc/moc
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/release/

####### Files

SOURCES       = src/Main.cpp \
		src/MemChunk.cpp \
		src/ListenerAnnouncer.cpp \
		src/PropertyList.cpp \
		src/ArchiveManagerFrame.cpp \
		src/FileBrowserFrame.cpp \
		src/MainWindow.cpp \
		src/Archive.cpp \
		src/ArchiveEntry.cpp \
		src/WadArchive.cpp src/moc/moc_ArchiveManagerFrame.cpp \
		src/moc/moc_FileBrowserFrame.cpp \
		src/moc/moc_MainWindow.cpp
OBJECTS       = obj/release/Main.o \
		obj/release/MemChunk.o \
		obj/release/ListenerAnnouncer.o \
		obj/release/PropertyList.o \
		obj/release/ArchiveManagerFrame.o \
		obj/release/FileBrowserFrame.o \
		obj/release/MainWindow.o \
		obj/release/Archive.o \
		obj/release/ArchiveEntry.o \
		obj/release/WadArchive.o \
		obj/release/moc_ArchiveManagerFrame.o \
		obj/release/moc_FileBrowserFrame.o \
		obj/release/moc_MainWindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		slade-qt.pro
QMAKE_TARGET  = slade-qt
DESTDIR       = bin/
TARGET        = bin/slade-qt

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: slade-qt.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix DESTDIR=./bin MOC_DIR=./src/moc CONFIG+=release OBJECTS_DIR=./obj/release -o Makefile slade-qt.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix DESTDIR=./bin MOC_DIR=./src/moc CONFIG+=release OBJECTS_DIR=./obj/release -o Makefile slade-qt.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/release/slade-qt1.0.0 || $(MKDIR) obj/release/slade-qt1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/release/slade-qt1.0.0/ && $(COPY_FILE) --parents src/Main.h src/MemChunk.h src/ListenerAnnouncer.h src/PropertyList.h src/ArchiveManagerFrame.h src/FileBrowserFrame.h src/MainWindow.h src/Archive.h src/ArchiveEntry.h src/WadArchive.h obj/release/slade-qt1.0.0/ && $(COPY_FILE) --parents src/Main.cpp src/MemChunk.cpp src/ListenerAnnouncer.cpp src/PropertyList.cpp src/ArchiveManagerFrame.cpp src/FileBrowserFrame.cpp src/MainWindow.cpp src/Archive.cpp src/ArchiveEntry.cpp src/WadArchive.cpp obj/release/slade-qt1.0.0/ && (cd `dirname obj/release/slade-qt1.0.0` && $(TAR) slade-qt1.0.0.tar slade-qt1.0.0 && $(COMPRESS) slade-qt1.0.0.tar) && $(MOVE) `dirname obj/release/slade-qt1.0.0`/slade-qt1.0.0.tar.gz . && $(DEL_FILE) -r obj/release/slade-qt1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: src/moc/moc_ArchiveManagerFrame.cpp src/moc/moc_FileBrowserFrame.cpp src/moc/moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) src/moc/moc_ArchiveManagerFrame.cpp src/moc/moc_FileBrowserFrame.cpp src/moc/moc_MainWindow.cpp
src/moc/moc_ArchiveManagerFrame.cpp: src/ArchiveManagerFrame.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ArchiveManagerFrame.h -o src/moc/moc_ArchiveManagerFrame.cpp

src/moc/moc_FileBrowserFrame.cpp: src/FileBrowserFrame.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/FileBrowserFrame.h -o src/moc/moc_FileBrowserFrame.cpp

src/moc/moc_MainWindow.cpp: src/ArchiveManagerFrame.h \
		src/MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/MainWindow.h -o src/moc/moc_MainWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/release/Main.o: src/Main.cpp src/Main.h \
		src/MemChunk.h \
		src/MainWindow.h \
		src/ArchiveManagerFrame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/release/Main.o src/Main.cpp

obj/release/MemChunk.o: src/MemChunk.cpp src/Main.h \
		src/MemChunk.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/release/MemChunk.o src/MemChunk.cpp

obj/release/ListenerAnnouncer.o: src/ListenerAnnouncer.cpp src/Main.h \
		src/MemChunk.h \
		src/ListenerAnnouncer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/release/ListenerAnnouncer.o src/ListenerAnnouncer.cpp

obj/release/PropertyList.o: src/PropertyList.cpp src/Main.h \
		src/MemChunk.h \
		src/PropertyList.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/release/PropertyList.o src/PropertyList.cpp

obj/release/ArchiveManagerFrame.o: src/ArchiveManagerFrame.cpp src/Main.h \
		src/MemChunk.h \
		src/ArchiveManagerFrame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/release/ArchiveManagerFrame.o src/ArchiveManagerFrame.cpp

obj/release/FileBrowserFrame.o: src/FileBrowserFrame.cpp src/Main.h \
		src/MemChunk.h \
		src/FileBrowserFrame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/release/FileBrowserFrame.o src/FileBrowserFrame.cpp

obj/release/MainWindow.o: src/MainWindow.cpp src/Main.h \
		src/MemChunk.h \
		src/MainWindow.h \
		src/ArchiveManagerFrame.h \
		src/FileBrowserFrame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/release/MainWindow.o src/MainWindow.cpp

obj/release/Archive.o: src/Archive.cpp src/Main.h \
		src/MemChunk.h \
		src/Archive.h \
		src/ArchiveEntry.h \
		src/ListenerAnnouncer.h \
		src/PropertyList.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/release/Archive.o src/Archive.cpp

obj/release/ArchiveEntry.o: src/ArchiveEntry.cpp src/Main.h \
		src/MemChunk.h \
		src/Archive.h \
		src/ArchiveEntry.h \
		src/ListenerAnnouncer.h \
		src/PropertyList.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/release/ArchiveEntry.o src/ArchiveEntry.cpp

obj/release/WadArchive.o: src/WadArchive.cpp src/Main.h \
		src/MemChunk.h \
		src/WadArchive.h \
		src/Archive.h \
		src/ArchiveEntry.h \
		src/ListenerAnnouncer.h \
		src/PropertyList.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/release/WadArchive.o src/WadArchive.cpp

obj/release/moc_ArchiveManagerFrame.o: src/moc/moc_ArchiveManagerFrame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/release/moc_ArchiveManagerFrame.o src/moc/moc_ArchiveManagerFrame.cpp

obj/release/moc_FileBrowserFrame.o: src/moc/moc_FileBrowserFrame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/release/moc_FileBrowserFrame.o src/moc/moc_FileBrowserFrame.cpp

obj/release/moc_MainWindow.o: src/moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/release/moc_MainWindow.o src/moc/moc_MainWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

