#############################################################################
# Makefile for building: Debug/slade
# Generated by qmake (2.01a) (Qt 4.6.2) on: Sun Apr 25 03:31:09 2010
# Project:  slade.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o slade.mk slade.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -W -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -W -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = Debug/

####### Files

SOURCES       = src/Main.cpp \
		src/MemChunk.cpp \
		src/ListenerAnnouncer.cpp \
		src/PropertyList.cpp \
		src/ArchiveManagerFrame.cpp \
		src/MainWindow.cpp \
		src/Archive.cpp \
		src/ArchiveEntry.cpp \
		src/WadArchive.cpp moc_ArchiveManagerFrame.cpp \
		moc_MainWindow.cpp
OBJECTS       = Debug/Main.o \
		Debug/MemChunk.o \
		Debug/ListenerAnnouncer.o \
		Debug/PropertyList.o \
		Debug/ArchiveManagerFrame.o \
		Debug/MainWindow.o \
		Debug/Archive.o \
		Debug/ArchiveEntry.o \
		Debug/WadArchive.o \
		Debug/moc_ArchiveManagerFrame.o \
		Debug/moc_MainWindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		slade.pro
QMAKE_TARGET  = slade
DESTDIR       = Debug/
TARGET        = Debug/slade

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: slade.mk $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) Debug/ || $(MKDIR) Debug/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

slade.mk: slade.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o slade.mk slade.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix -o slade.mk slade.pro

dist: 
	@$(CHK_DIR_EXISTS) Debug/slade1.0.0 || $(MKDIR) Debug/slade1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) Debug/slade1.0.0/ && $(COPY_FILE) --parents src/Main.h src/MemChunk.h src/ListenerAnnouncer.h src/PropertyList.h src/ArchiveManagerFrame.h src/MainWindow.h src/Archive.h src/ArchiveEntry.h src/WadArchive.h Debug/slade1.0.0/ && $(COPY_FILE) --parents src/Main.cpp src/MemChunk.cpp src/ListenerAnnouncer.cpp src/PropertyList.cpp src/ArchiveManagerFrame.cpp src/MainWindow.cpp src/Archive.cpp src/ArchiveEntry.cpp src/WadArchive.cpp Debug/slade1.0.0/ && (cd `dirname Debug/slade1.0.0` && $(TAR) slade1.0.0.tar slade1.0.0 && $(COMPRESS) slade1.0.0.tar) && $(MOVE) `dirname Debug/slade1.0.0`/slade1.0.0.tar.gz . && $(DEL_FILE) -r Debug/slade1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) slade.mk


/usr/bin/moc-qt4:
	(cd $(QTDIR)/src/tools/moc && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_moc_header_make_all: moc_ArchiveManagerFrame.cpp moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ArchiveManagerFrame.cpp moc_MainWindow.cpp
moc_ArchiveManagerFrame.cpp: src/ArchiveManagerFrame.h \
		/usr/bin/moc-qt4
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/ArchiveManagerFrame.h -o moc_ArchiveManagerFrame.cpp

moc_MainWindow.cpp: src/ArchiveManagerFrame.h \
		src/MainWindow.h \
		/usr/bin/moc-qt4
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/MainWindow.h -o moc_MainWindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Debug/Main.o: src/Main.cpp src/Main.h \
		src/MemChunk.h \
		src/MainWindow.h \
		src/ArchiveManagerFrame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/Main.o src/Main.cpp

Debug/MemChunk.o: src/MemChunk.cpp src/Main.h \
		src/MemChunk.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/MemChunk.o src/MemChunk.cpp

Debug/ListenerAnnouncer.o: src/ListenerAnnouncer.cpp src/Main.h \
		src/MemChunk.h \
		src/ListenerAnnouncer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/ListenerAnnouncer.o src/ListenerAnnouncer.cpp

Debug/PropertyList.o: src/PropertyList.cpp src/Main.h \
		src/MemChunk.h \
		src/PropertyList.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/PropertyList.o src/PropertyList.cpp

Debug/ArchiveManagerFrame.o: src/ArchiveManagerFrame.cpp src/Main.h \
		src/MemChunk.h \
		src/ArchiveManagerFrame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/ArchiveManagerFrame.o src/ArchiveManagerFrame.cpp

Debug/MainWindow.o: src/MainWindow.cpp src/Main.h \
		src/MemChunk.h \
		src/MainWindow.h \
		src/ArchiveManagerFrame.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/MainWindow.o src/MainWindow.cpp

Debug/Archive.o: src/Archive.cpp src/Main.h \
		src/MemChunk.h \
		src/Archive.h \
		src/ArchiveEntry.h \
		src/ListenerAnnouncer.h \
		src/PropertyList.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/Archive.o src/Archive.cpp

Debug/ArchiveEntry.o: src/ArchiveEntry.cpp src/Main.h \
		src/MemChunk.h \
		src/Archive.h \
		src/ArchiveEntry.h \
		src/ListenerAnnouncer.h \
		src/PropertyList.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/ArchiveEntry.o src/ArchiveEntry.cpp

Debug/WadArchive.o: src/WadArchive.cpp src/Main.h \
		src/MemChunk.h \
		src/WadArchive.h \
		src/Archive.h \
		src/ArchiveEntry.h \
		src/ListenerAnnouncer.h \
		src/PropertyList.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/WadArchive.o src/WadArchive.cpp

Debug/moc_ArchiveManagerFrame.o: moc_ArchiveManagerFrame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/moc_ArchiveManagerFrame.o moc_ArchiveManagerFrame.cpp

Debug/moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debug/moc_MainWindow.o moc_MainWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

